In [1]:
___Author___='LumberJack Jyss'

In [2]:
print('Global Optimized LumberJack Equities Method\n°OoO_FOREX_Oo0°\nLumberJack Jyss 5779(c)')

Global Optimized LumberJack Equities Method
°OoO_FOREX_Oo0°
LumberJack Jyss 5779(c)


In [28]:
print('Importation des librairies...')
import numpy as np
import pandas as pd
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import statsmodels.api as sm
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('TkAgg')
import seaborn as sns
%matplotlib inline
print('Librairies importées')

Importation des librairies...
Librairies importées


In [7]:
# SCRAPING DES DONNES BRUTES
gbpjpy = pd.read_csv('gbpjpy_15mn_1Y.csv')
gbpjpy = gbpjpy.set_index('Date')
gbpjpy = gbpjpy.iloc[:,1:-1]
gbpusd = pd.read_csv('gbpusd_15mn_1Y.csv')
gbpusd = gbpusd.set_index('Date')
gbpusd = gbpusd.iloc[:-2,1:-1]
eurusd = pd.read_csv('eurusd_15mn_1Y.csv')
eurusd = eurusd.set_index('Date')
eurusd = eurusd.iloc[:-2,1:-1]
df = pd.DataFrame({'x':gbpjpy['Close'],'y':gbpusd['Close'],'z':eurusd['Close']})

In [10]:
coint = coint_johansen(df,0,1)

In [12]:
coint.eig

array([5.59898533e-04, 3.77733176e-04, 9.53621067e-05])

In [13]:
coint.evec

array([[ -0.10471411,  -0.55159454,   0.10909666],
       [-26.44295974,  51.0836691 , -51.19829245],
       [-15.8941922 ,   9.00249642,  63.75593769]])

In [14]:
coint.lr1

array([25.29235208, 11.58275754,  2.33448032])

In [15]:
coint.lr2

array([13.70959455,  9.24827721,  2.33448032])

In [16]:
coint.cvt

array([[27.0669, 29.7961, 35.4628],
       [13.4294, 15.4943, 19.9349],
       [ 2.7055,  3.8415,  6.6349]])

In [17]:
coint.cvm

array([[18.8928, 21.1314, 25.865 ],
       [12.2971, 14.2639, 18.52  ],
       [ 2.7055,  3.8415,  6.6349]])

In [21]:
coint.r0t

array([[-1.45811546e-02,  5.88626803e-05, -2.53913502e-04],
       [-4.17845387e-02,  5.89436934e-05,  1.69434290e-04],
       [ 8.49666860e-03,  1.65666280e-04,  2.75969339e-04],
       ...,
       [-5.66546852e-02, -9.84586726e-05, -4.45947868e-05],
       [ 1.97270708e-01,  4.59958941e-04,  8.36574956e-04],
       [-3.34091141e-02, -4.81621280e-04,  1.50028677e-04]])

In [23]:
coint.ind

array([0, 1, 2])

In [24]:
coint.meth

'johansen'

In [31]:
results = sm.OLS(gbpjpy['Close'], gbpusd['Close']).fit()

In [35]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Close   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.553e+08
Date:                Wed, 15 May 2019   Prob (F-statistic):               0.00
Time:                        14:41:26   Log-Likelihood:                -49417.
No. Observations:               24481   AIC:                         9.884e+04
Df Residuals:                   24480   BIC:                         9.884e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Close        111.2406      0.009   1.25e+04      0.000     111.223     111.258
==============================================================================
Omnibus:                      639.703   Durbin-Watson:                   0.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              325.798
Skew:                          -0.055   Prob(JB):                     1.79e-71
Kurtosis:                       2.445   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
coint.rkt

x         y         z
Date                                            
20180506  23:30:00  2.609233  0.049417  0.047476
20180506  23:45:00  2.609635  0.049504  0.047376
20180507  00:00:00  2.594378  0.049715  0.047390
20180507  00:15:00  2.563840  0.049649  0.047513
20180507  00:30:00  2.541510  0.049252  0.047287
20180507  00:45:00  2.604015  0.049598  0.047396
20180507  01:00:00  2.603853  0.049283  0.047193
20180507  01:15:00  2.688593  0.049525  0.047278
20180507  01:30:00  2.703114  0.049783  0.047373
20180507  01:45:00  2.624079  0.049256  0.047031
20180507  02:00:00  2.637282  0.050155  0.047656
20180507  02:15:00  2.512877  0.049941  0.047785
20180507  02:30:00  2.497386  0.050002  0.047796
20180507  02:45:00  2.538812  0.050836  0.048327
20180507  03:00:00  2.478407  0.051510  0.048921
20180507  03:15:00  2.336105  0.050834  0.048604
20180507  03:30:00  2.353542  0.050613  0.048504
20180507  03:45:00  2.408547  0.050246  0.047974
20180507  04:00:00  2.564765  0.051223  0.048436
20180507  04:15:00  2.575625  0.051524  0.048671
20180507  04:30:00  2.573951  0.051466  0.048619
20180507  04:45:00  2.607449  0.051372  0.048566
20180507  05:00:00  2.700056  0.051915  0.048828
20180507  05:15:00  2.712224  0.052108  0.048935
20180507  05:30:00  2.696218  0.052080  0.048882
20180507  05:45:00  2.626486  0.051396  0.048290
20180507  06:00:00  2.640100  0.050745  0.047686
20180507  06:15:00  2.707408  0.050810  0.047638
20180507  06:30:00  2.738621  0.050651  0.047428
20180507  06:45:00  2.781353  0.050914  0.047468
...                      ...       ...       ...
20190503  16:30:00  0.425314  0.003722 -0.030614
20190503  16:45:00  0.769244  0.006273 -0.029769
20190503  17:00:00  1.194093  0.010125 -0.028983
20190503  17:15:00  1.199481  0.011697 -0.029278
20190503  17:30:00  1.025666  0.009632 -0.030067
20190503  17:45:00  1.106725  0.009604 -0.029911
20190503  18:00:00  1.110841  0.009689 -0.029794
20190503  18:15:00  1.189162  0.010282 -0.029303
20190503  18:30:00  1.264487  0.011269 -0.028841
20190503  18:45:00  1.182304  0.011036 -0.029109
20190503  19:00:00  1.182694  0.010710 -0.029073
20190503  19:15:00  1.202937  0.010896 -0.029156
20190503  19:30:00  1.249866  0.011325 -0.029113
20190503  19:45:00  1.248667  0.011665 -0.029192
20190503  20:00:00  1.276974  0.012174 -0.029170
20190503  20:15:00  1.230782  0.012314 -0.029314
20190503  20:30:00  1.251643  0.012718 -0.028867
20190503  20:45:00  1.180098  0.012445 -0.029074
20190503  21:00:00  1.228026  0.012744 -0.029006
20190503  21:15:00  1.235534  0.012906 -0.028936
20190503  21:30:00  1.233854  0.012826 -0.028859
20190503  21:45:00  1.227763  0.012794 -0.028728
20190503  22:00:00  1.218611  0.012737 -0.028578
20190503  22:15:00  1.222364  0.012837 -0.028383
20190503  22:30:00  1.204253  0.012661 -0.028349
20190503  22:45:00  1.283770  0.013177 -0.028246
20190505  23:15:00  1.095327  0.015109 -0.028030
20190505  23:30:00  0.524739  0.011812 -0.030633
20190505  23:45:00  0.530443  0.012182 -0.030499
20190506  00:00:00  0.534328  0.011552 -0.030627

[24479 rows x 3 columns]